import {test} from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {PassThrough} from 'node:stream';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {JobHost,decoder,encodeFrame,codexArgs,MAX_BYTES,MAX_FRAME} from './host.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
async function fixture(t,spawnProcess){const root=await fs.mkdtemp(path.join(os.tmpdir(),'occ-bridge-test-'));const h=new JobHost({dataRoot:root,codexPath:'codex.exe'},{spawnProcess});t.after(async()=>{await h.close();assert.ok(path.basename(root).startsWith('occ-bridge-test-'));await fs.rm(root,{recursive:true,force:true});});return h;}
async function stage(h,text='fixture',extra={}){const input=Buffer.from(text);const {job}=await h.handle({type:'begin',instruction:'Analyze synthetic fixture only',mode:'analyze',bytes:input.length,sha256:sha(input),...extra});if(input.length)await h.handle({type:'append',jobId:job.id,offset:0,base64:input.toString('base64')});return job.id;}
const wait=async(fn)=>{for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('Timeout');};
function fakeProcess({onStart,reply='fixture result',exitCode=0,hold=false}={}){return (exe,args,opts)=>{onStart?.(exe,args,opts);const child=new EventEmitter();child.stdin=new PassThrough();child.stdout=new PassThrough();child.stderr=new PassThrough();child.kill=()=>{setImmediate(()=>child.emit('close',1));};child.stdin.on('finish',async()=>{if(hold)return;await fs.writeFile(path.join(opts.cwd,'result.txt'),reply);child.emit('close',exitCode);});return child;};}
test('framing handles split headers, split UTF-8, and multiple messages',()=>{const values=[],read=decoder(v=>values.push(v),e=>{throw e;});const b=Buffer.concat([encodeFrame({text:'Привет 👋'}),encodeFrame({ok:true})]);for(const c of b)read(Buffer.from([c]));assert.deepEqual(values,[{text:'Привет 👋'},{ok:true}]);});
test('framing rejects oversized and invalid JSON before dispatch',()=>{let error,count=0;const read=decoder(()=>count++,e=>error=e);const header=Buffer.alloc(4);header.writeUInt32LE(MAX_FRAME+1);read(header);assert.match(error.message,/FRAME_LIMIT/);assert.equal(count,0);let malformed;decoder(()=>{},e=>malformed=e)(Buffer.from([1,0,0,0,123]));assert.ok(malformed);});
test('commands cannot inject executable paths or unsafe sandbox modes',()=>{assert.throws(()=>codexArgs('x','danger-full-access'),/MODE/);const args=codexArgs('C:/a b','build');assert.ok(args.includes('workspace-write'));assert.ok(!args.some(a=>a.includes('dangerously')));assert.equal(args.at(-1),'-');});
test('oversized input, instruction and invalid mode rejected',async t=>{const h=await fixture(t);for(const extra of [{bytes:MAX_BYTES+1},{instruction:'a'.repeat(16001)},{mode:'shell'},{sha256:'bad'}])await assert.rejects(stage(h,'x',extra),/SCHEMA/);assert.equal(h.jobs.size,0);});
test('out-of-order, corrupt and incomplete payloads cannot run',async t=>{const h=await fixture(t);const {job}=await h.handle({type:'begin',instruction:'x',mode:'analyze',bytes:3,sha256:sha(Buffer.from('abc'))});await assert.rejects(h.handle({type:'append',jobId:job.id,offset:1,base64:'YWJj'}),/ORDER/);await assert.rejects(h.handle({type:'run',jobId:job.id}),/INTEGRITY/);await h.handle({type:'append',jobId:job.id,offset:0,base64:'eHl6'});await assert.rejects(h.handle({type:'run',jobId:job.id}),/INTEGRITY/);});
test('production job writes exact input, spawns no shell, returns verified chunks',async t=>{let calls=0;const input='Привет 👋\r\n  + code\\_value';const output='Ответ\r\n';const h=await fixture(t,fakeProcess({reply:output,onStart:(exe,args,opts)=>{calls++;assert.equal(exe,'codex.exe');assert.equal(opts.shell,false);assert.equal(opts.windowsHide,true);assert.ok(args.includes('read-only'));assert.equal(opts.env.OPENAI_API_KEY,undefined);}}));const id=await stage(h,input);await h.handle({type:'run',jobId:id});await wait(()=>h.jobs.get(id).state==='COMPLETE');assert.equal(calls,1);assert.deepEqual(await fs.readFile(path.join(h.jobs.get(id).directory,'input.txt')),Buffer.from(input));const r=await h.handle({type:'result',jobId:id,offset:0});assert.deepEqual(Buffer.from(r.base64,'base64'),Buffer.from(output));assert.equal(r.sha256,sha(Buffer.from(output)));await assert.rejects(h.handle({type:'run',jobId:id}),/ALREADY/);});
test('queue runs one job at a time and cancel releases it',async t=>{let calls=0;const h=await fixture(t,fakeProcess({hold:true,onStart:()=>calls++}));const a=await stage(h),b=await stage(h);await h.handle({type:'run',jobId:a});await h.handle({type:'run',jobId:b});assert.equal(calls,1);assert.equal(h.jobs.get(b).state,'QUEUED');await h.handle({type:'cancel',jobId:a});await wait(()=>calls===2);assert.equal(h.jobs.get(a).state,'CANCELLED');await h.handle({type:'cancel',jobId:b});});
test('failed Codex job is not successful and cannot export',async t=>{const h=await fixture(t,fakeProcess({exitCode:1}));const id=await stage(h);await h.handle({type:'run',jobId:id});await wait(()=>h.jobs.get(id).state==='FAILED');await assert.rejects(h.handle({type:'result',jobId:id,offset:0}),/NOT_READY/);});
test('discard deletes only owned job files and later access fails',async t=>{const h=await fixture(t);const id=await stage(h);const dir=h.jobs.get(id).directory;await h.handle({type:'discard',jobId:id});await assert.rejects(fs.stat(dir));await assert.rejects(h.handle({type:'run',jobId:id}),/NOT_FOUND/);await assert.rejects(h.remove({directory:path.dirname(h.config.dataRoot)}),/BOUNDARY/);});
test('job cap and disconnect clear temporary jobs',async t=>{const h=await fixture(t);for(let i=0;i<5;i++)await stage(h);await assert.rejects(stage(h),/JOB_LIMIT/);await h.close();assert.deepEqual(await fs.readdir(h.config.dataRoot),[]);await assert.rejects(h.handle({type:'hello'}),/CLOSED/);});
