import path from 'node:path';
import {spawn} from 'node:child_process';

export const QUALIFICATION_COMMANDS=Object.freeze(['qualification.inspect']);
export const QUALIFICATION_INPUT_BYTES=64*1024,QUALIFICATION_OUTPUT_BYTES=512*1024,QUALIFICATION_TIMEOUT_MS=210000;
const ALLOWED_TEXT=new Set(['проверь готовность бота','проверь квалификацию бота','check bot readiness','qualify and report']);
const sha=/^[a-f0-9]{64}$/;
const task=/^[A-Za-z0-9][A-Za-z0-9_-]{0,79}$/;
const sourceKeys=['source_id','version','sha256'];
const normalize=text=>text.trim().replace(/\s+/gu,' ').toLocaleLowerCase('und');
export function qualificationEnvironment(source=process.env){const env={PYTHONUTF8:'1',PYTHONIOENCODING:'utf-8'};for(const name of ['PATH','SystemRoot','SYSTEMROOT','WINDIR','TEMP','TMP','LANG','LC_ALL'])if(typeof source[name]==='string')env[name]=source[name];return env;}
function sourceRef(value){if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).some(k=>!sourceKeys.includes(k))||sourceKeys.some(k=>!Object.hasOwn(value,k)))throw Error('QUALIFICATION_SOURCE_REF_SCHEMA');if(typeof value.source_id!=='string'||!value.source_id||value.source_id.length>160||typeof value.version!=='string'||!value.version||value.version.length>160||!sha.test(value.sha256))throw Error('QUALIFICATION_SOURCE_REF_SCHEMA');return {source_id:value.source_id,version:value.version,sha256:value.sha256};}
function requestFrom(message){const allowed=['type','requestId','taskId','text','sourceRefs'];if(!message||typeof message!=='object'||message.type!=='qualification.inspect'||Object.keys(message).some(k=>!allowed.includes(k)))throw Error('QUALIFICATION_SCHEMA');if(typeof message.taskId!=='string'||!task.test(message.taskId)||typeof message.text!=='string'||message.text.length>256||!ALLOWED_TEXT.has(normalize(message.text))||!Array.isArray(message.sourceRefs)||message.sourceRefs.length>32)throw Error('QUALIFICATION_SCHEMA');const refs=message.sourceRefs.map(sourceRef);const fingerprints=new Set(refs.map(v=>JSON.stringify(v)));if(fingerprints.size!==refs.length)throw Error('QUALIFICATION_SOURCE_REF_DUPLICATE');return {schema:'occ.native-qualification-request.v1',task_id:message.taskId,text:message.text,source_refs:refs};}
export class QualificationBridge{
 constructor(config,{spawnProcess=spawn}={}){this.config=config;this.spawnProcess=spawnProcess;this.children=new Map();this.closed=false;if(config?.enabled===true&&['pythonPath','adapterPath','profilePath'].some(key=>typeof config[key]!=='string'||!path.isAbsolute(config[key])||config[key].includes('\0')))throw Error('QUALIFICATION_OPERATOR_CONFIG_REQUIRED');}
 get enabled(){return this.config?.enabled===true;}
 async handle(message){if(this.closed)throw Error('CLOSED');if(!this.enabled)throw Error('QUALIFICATION_UNAVAILABLE');const request=requestFrom(message);const input=Buffer.from(JSON.stringify(request));if(input.length>QUALIFICATION_INPUT_BYTES)throw Error('QUALIFICATION_INPUT_LIMIT');const argv=['-I','-X','utf8',this.config.adapterPath,'--profile',this.config.profilePath];return new Promise((resolve,reject)=>{let child,timer,done=false,total=0;const output=[];const finish=(error,value)=>{if(done)return;done=true;clearTimeout(timer);if(child)this.children.delete(child);error?reject(error):resolve(value);};const stop=()=>{try{child.kill('SIGKILL');}catch{/* already exited */}};try{child=this.spawnProcess(this.config.pythonPath,argv,{env:qualificationEnvironment(),shell:false,windowsHide:true,stdio:['pipe','pipe','pipe']});this.children.set(child,()=>{stop();finish(Error('CLOSED'));});child.once('error',()=>finish(Error('QUALIFICATION_PROCESS_FAILED')));const consume=(bytes,keep)=>{if(done)return;total+=bytes.length;if(total>QUALIFICATION_OUTPUT_BYTES){stop();finish(Error('QUALIFICATION_OUTPUT_LIMIT'));}else if(keep)output.push(bytes);};child.stdout.on('data',bytes=>consume(bytes,true));child.stderr.on('data',bytes=>consume(bytes,false));child.once('close',code=>{if(done)return;try{const parsed=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(Buffer.concat(output)));if(code!==0){const error=parsed?.ok===false&&typeof parsed.error==='string'&&/^[A-Z0-9_]{1,100}$/.test(parsed.error)?parsed.error:'QUALIFICATION_PROCESS_FAILED';throw Error(error);}if(parsed?.ok!==true||!parsed.result||parsed.result.schema!=='occ.native-qualification-result.v1'||parsed.result.request_id!==request.task_id||!['BLOCKED','PAPER_PASS'].includes(parsed.result.domain_verdict)||parsed.result.qualified!==false||parsed.result.release_authorized!==false||parsed.result.live_authorized!==false||parsed.result.transactions_sent!==0)throw Error('QUALIFICATION_RESULT_SCHEMA');finish(null,{qualification:parsed.result});}catch(error){finish(error.message?.startsWith('QUALIFICATION_')?error:Error('QUALIFICATION_INVALID_RESPONSE'));}});timer=setTimeout(()=>{stop();finish(Error('QUALIFICATION_TIMEOUT'));},QUALIFICATION_TIMEOUT_MS);timer.unref?.();child.stdin.on('error',()=>{});child.stdin.end(input);}catch{if(child)stop();finish(Error('QUALIFICATION_PROCESS_FAILED'));}});}
 close(){this.closed=true;for(const cancel of this.children.values())cancel();this.children.clear();}
}
