import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {packageTreeSha256,verifyInstalledPackage,qualifyInstalledBrowserTransport,IDENTITY_SCHEMA,TREE_ALGORITHM,QUALIFY_RESULT_SCHEMA,HOST_NAME} from '../library/browser-transport-qualification.mjs';

const encoder=new TextEncoder(),ids=Array.from({length:20},(_,i)=>`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`),extensionId='a'.repeat(32);
async function packageFixture(){const source=[{path:'background.js',bytes:encoder.encode('background')},{path:'manifest.json',bytes:encoder.encode('{"version":"0.13.0"}')}],tree=await packageTreeSha256(source),files=[];for(const entry of source)files.push({path:entry.path,bytes:entry.bytes.length,sha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',entry.bytes))].map(x=>x.toString(16).padStart(2,'0')).join('')});const identity={schema:IDENTITY_SCHEMA,version:'0.13.0',algorithm:TREE_ALGORITHM,package_tree_sha256:tree,files},map=new Map(source.map(x=>[x.path,x.bytes]));map.set('PACKAGE_IDENTITY.json',encoder.encode(JSON.stringify(identity)));return {tree,map,identity};}
function event(){const listeners=new Set();return {addListener:f=>listeners.add(f),removeListener:f=>listeners.delete(f),fire:value=>{for(const f of [...listeners])f(value);}};}
function chromeFixture(pkg,{mutate=()=>{},sameSession=false,remove=true,permission=true}={}){let allowed=permission,connections=0;return {permissions:{contains:async()=>allowed,remove:async()=>{if(remove)allowed=false;return remove;}},runtime:{id:extensionId,getManifest:()=>({version:'0.13.0'}),connectNative:name=>{assert.equal(name,HOST_NAME);const onMessage=event(),onDisconnect=event(),session=sameSession?ids[15]:ids[15+connections++];return {onMessage,onDisconnect,postMessage(request){let qualification={schema:QUALIFY_RESULT_SCHEMA,nonce:request.nonce,extension_id:request.extensionId,extension_version:request.extensionVersion,package_tree_sha256:request.packageTreeSha256,host_name:HOST_NAME,session_id:session,action_dispatch_allowed:false};qualification=mutate(qualification,request)||qualification;queueMicrotask(()=>onMessage.fire({requestId:request.requestId,ok:true,qualification}));},disconnect(){queueMicrotask(()=>onDisconnect.fire());}};}}};}

test('package identity verifies every installed byte and exact tree digest',async()=>{const pkg=await packageFixture();assert.deepEqual(await verifyInstalledPackage(pkg.map.get('PACKAGE_IDENTITY.json'),path=>pkg.map.get(path),pkg.tree),{version:'0.13.0',package_tree_sha256:pkg.tree,file_count:2});});
test('tree digest algorithm matches the language-neutral fixture',async()=>{assert.equal(await packageTreeSha256([{path:'a',bytes:encoder.encode('x')},{path:'b',bytes:encoder.encode('y')}]),'bd7ae9a9949344483a8b1c2bf794dbd7c2449b53af3908d954e6142a1ea89a0a');});
test('tampered or omitted installed file fails closed',async()=>{const pkg=await packageFixture();pkg.map.set('background.js',encoder.encode('changed'));await assert.rejects(verifyInstalledPackage(pkg.map.get('PACKAGE_IDENTITY.json'),path=>pkg.map.get(path),pkg.tree),error=>error.code==='PACKAGE_FILE_MISMATCH');});
test('identity rejects traversal duplicate ordering extra fields and wrong expected hash',async()=>{const pkg=await packageFixture();for(const mutate of [v=>v.files[0].path='../x',v=>v.files.reverse(),v=>v.extra=true,v=>v.package_tree_sha256='f'.repeat(64)]){const value=structuredClone(pkg.identity);mutate(value);await assert.rejects(verifyInstalledPackage(encoder.encode(JSON.stringify(value)),path=>pkg.map.get(path),pkg.tree));}});
test('qualification proves two fresh bindings then revokes permission without dispatch',async()=>{const pkg=await packageFixture();let next=0;const receipt=await qualifyInstalledBrowserTransport({chromeApi:chromeFixture(pkg),readPackageFile:path=>pkg.map.get(path),expectedPackageTreeSha256:pkg.tree,randomUUID:()=>ids[next++]});assert.equal(receipt.state,'QUALIFIED');assert.equal(receipt.handshakes,2);assert.equal(receipt.fresh_reconnect,true);assert.equal(receipt.permission_revoked,true);assert.equal(receipt.action_dispatch_allowed,false);assert.equal(receipt.package_tree_sha256,pkg.tree);});
test('wrong nonce hash extension version host or dispatch claim is rejected',async()=>{for(const [field,value] of [['nonce',ids[19]],['package_tree_sha256','f'.repeat(64)],['extension_id','b'.repeat(32)],['extension_version','9.9.9'],['host_name','other.host'],['action_dispatch_allowed',true]]){const pkg=await packageFixture(),chromeApi=chromeFixture(pkg,{mutate:result=>({...result,[field]:value})});let next=0;await assert.rejects(qualifyInstalledBrowserTransport({chromeApi,readPackageFile:path=>pkg.map.get(path),expectedPackageTreeSha256:pkg.tree,randomUUID:()=>ids[next++]}),error=>error.code==='TRANSPORT_BINDING_MISMATCH');}});
test('permission absence stale reconnect and failed revoke never qualify',async()=>{for(const options of [{permission:false},{sameSession:true},{remove:false}]){const pkg=await packageFixture();let next=0;await assert.rejects(qualifyInstalledBrowserTransport({chromeApi:chromeFixture(pkg,options),readPackageFile:path=>pkg.map.get(path),expectedPackageTreeSha256:pkg.tree,randomUUID:()=>ids[next++]}));}});
test('disconnect must be observed before reconnect can qualify',async()=>{const pkg=await packageFixture(),chromeApi=chromeFixture(pkg);chromeApi.runtime.connectNative=()=>{const onMessage=event(),onDisconnect=event();return {onMessage,onDisconnect,postMessage(request){queueMicrotask(()=>onMessage.fire({requestId:request.requestId,ok:true,qualification:{schema:QUALIFY_RESULT_SCHEMA,nonce:request.nonce,extension_id:request.extensionId,extension_version:request.extensionVersion,package_tree_sha256:request.packageTreeSha256,host_name:HOST_NAME,session_id:ids[15],action_dispatch_allowed:false}}));},disconnect(){}};};let next=0;await assert.rejects(qualifyInstalledBrowserTransport({chromeApi,readPackageFile:path=>pkg.map.get(path),expectedPackageTreeSha256:pkg.tree,randomUUID:()=>ids[next++],timeoutMilliseconds:10}),/DISCONNECT_TIMEOUT/);});
test('production qualifier exposes no tabs scripting page action or network transport',()=>{const source=fs.readFileSync(new URL('../library/browser-transport-qualification.mjs',import.meta.url),'utf8');for(const forbidden of ['tabs.','scripting.','executeScript','fetch(','XMLHttpRequest','WebSocket','eval(','Function(','child_process'])assert.equal(source.includes(forbidden),false,forbidden);});
test('qualification page fetches only its own extension package and grants no action authority',()=>{const source=fs.readFileSync(new URL('../qualification.mjs',import.meta.url),'utf8');assert.match(source,/parsed\.protocol!==['"]chrome-extension:/);assert.match(source,/parsed\.host!==chrome\.runtime\.id/);assert.match(source,/action_dispatch_allowed:false/);for(const forbidden of ['tabs.','scripting.','executeScript','sendNativeMessage','eval(','Function('])assert.equal(source.includes(forbidden),false,forbidden);});
